name = "SurrogatedDistanceModels"
uuid = "0e04eddd-96ac-454e-8372-d12cc190ad6e"
authors = ["Eric S. Tellez <donsadit@gmail.com>"]
version = "0.1.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25"
Downloads = "^1.0"
JLD2 = "^0.4"
MultivariateStats = "0.10"
Polyester = "0.7"
SimilaritySearch = "0.11"
StatsAPI = "1.7"
StatsBase = "0.33"
Test = "^1.0"
julia = "^1.8"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Downloads", "JLD2", "Test"]

